version: '2'
services:
  tethys_in_docker_postgis:
#    restart: always
    container_name: tethys_in_docker_postgis
    image: ciwater/postgis:2.1.2
    # Do not remove following 2 lines. They are placeholders.
    ports:
    - "5435:5432"
    volumes:
      ## logs must be writable (better have 777 permission) or it can cause failed initialization
      ## of new db container: can not create tethys db accounts and tables
      - ./logs/:/var/log/supervisor
      - ./logs/:/var/log/postgis
      - ./logs/:/var/log/postgresql
      - ./postgis/postgresql.conf:/etc/postgresql/9.3/main/postgresql.conf
      - ./postgis/pg_hba.conf:/etc/postgresql/9.3/main/pg_hba.conf
      - ./postgis/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    env_file: ./postgis/postgis.env

  tethys_in_docker_main:
#    restart: always
#    hostname: 10.2.115.24
    container_name: tethys_in_docker_main
    build: ./tethys_main/
    image: tethys_in_docker_main
    environment:
        - PYTHONUNBUFFERED=TRUE
    # Do not remove following 2 lines. They are placeholders.
    ports:
    - "8000:8000"
    - "5555:5555"
    volumes:
      - ./tethys/:/tethys
      - ./tethys_main/settings.py:/tethys/tethys_apps/settings.py
      #- ./tethys_main/patches/backends/hs_restclient_helper.py:/tethys/tethys_services/backends/hs_restclient_helper.py
      #- ./tethys_main/patches/backends/hydroshare.py:/tethys/tethys_services/backends/hydroshare.py
      #- ./tethys_main/patches/backends/hydroshare_beta.py:/tethys/tethys_services/backends/hydroshare_beta.py
      #- ./tethys_main/patches/backends/hydroshare_playground.py:/tethys/tethys_services/backends/hydroshare_playground.py
      #- ./tethys_main/patches/login.html:/tethys/templates/tethys_portal/accounts/login.html
      #- ./tethys_main/patches/settings.html:/tethys/templates/tethys_portal/user/settings.html
      #- ./tethys_main/patches/profile.html:/tethys/templates/tethys_portal/user/profile.html
      #- ./tethys_main/patches/disconnect.html:/tethys/templates/tethys_portal/user/disconnect.html
      - ./tethys_main/patches/header.html:/tethys/templates/header.html
      - ./tethys_main/patches/footer.html:/tethys/templates/footer.html
      #- ./tethys_main/patches/test_hydroshare_backend.py:/tethys/tethys_portal/unit_tests/test_tethys_services/test_hydroshare_backend.py
      - ./tethys_main/patches/middleware.py:/tethys/tethys_portal/middleware.py
      - ./tethys_main/patches/hydroshare-logo-75.png:/tethys/static/tethys_portal/images/hydroshare-logo-75.png
      - ./tethys_main/:/tethys_main
      - ./tethys_main/gunicorn-supervisor.conf:/etc/supervisor/conf.d/gunicorn-supervisor.conf
      - ./tethys_main/patches/tethys_apps/__init__.py:/tethys/tethys_apps/__init__.py
      - ./tethys_main/patches/tethys_apps/celery.py:/tethys/tethys_apps/celery.py
      - ./static/:/var/www/tethys/static
      - ./apps/:/apps
      - ./logs/:/logs

      ## Development mode: MOUNT NWM data and subsetting query db
      - /media/sf_nwm_new_data:/projects/water/nwm/data/nomads
      - /home/drew/Desktop/nwm.sqlite:/nwm.sqlite

      ## Production mode: MOUNT NWM data and subsetting query db
      # - /projects/water/nwm/:/projects/water/nwm
      # - /home/hydroapp/nwm.sqlite:/nwm.sqlite

      # Do not remove following line. it is placeholder
      #_#_#_#<TETHYS_MAIN_MOUNT_RENCI_FOLDER>#_#_#_#

    # start django development server
    #_#_TETHYS_MAIN_USE_DJANGO_TESTING_SERVER_#_#command: runuser -u tethys-user -g tethys-group /bin/bash /tethys_main/run-server
    #command: python manage.py runserver 0.0.0.0:8000

    # start gunicore server
    #command: /tethys_main/run-gunicorn

    # start supervisor + gunicorn
    command: /tethys_main/startup

    depends_on:
      - tethys_in_docker_postgis

  tethys_in_docker_nginx:
#    restart: always
    image: nginx:1.11.5
    #image: zhiyuli/nginx-extras-lua-json:1.10
    container_name: tethys_in_docker_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs/:/certs
       # Do not remove following 3 lines. they are placeholders
      - ./nginx/certs/cert-chain.crt:/certs/cert-chain.crt
      - ./nginx/certs/server.crt:/certs/server.crt
      - ./nginx/certs/server.key:/certs/server.key
      - ./nginx/ssl.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/files/tethys_favicon.ico:/var/www/tethys_favicon.ico
      - ./nginx/files/error_500.html:/var/www/error_500.html
      - ./nginx/files/error_maintenance.html:/var/www/error_maintenance.html
      - ./static/:/var/www/tethys/static
      - ./logs/:/logs

    depends_on:
      - tethys_in_docker_main
      - tethys_in_docker_geoserver
      - tethys_in_docker_n52wps

  tethys_in_docker_geoserver:
#    restart: always
    image: zhiyuli/geoserver:2.8.2-clustered-1.8
    container_name: tethys_in_docker_geoserver
    # Do not remove following 6 lines. They are placeholders.
    ports:
    - "8181:8181"
    - "8081:8081"
    - "8082:8082"
    - "8083:8083"
    - "8084:8084"
    env_file: ./geoserver/geoserver.env
    volumes:
      - ./logs/:/var/log/nginx
      - ./logs/:/var/geoserver/logs
      - ./logs/:/var/log/supervisor

  tethys_in_docker_n52wps:
#    restart: always
    image: ciwater/n52wps:3.3.0
    container_name: tethys_in_docker_n52wps
    # Do not remove following 2 lines. They are placeholders.
    ports:
    - "8282:8080"
    env_file: ./n52wps/n52wps.env
    #volumes:
    #  - ./logs/n52wps/tomcat7/:/var/log/tomcat7
    #  - ./logs/n52wps/supervisor/:/var/log/supervisor
