version: '2'
services:
  tethys_in_docker_postgis:
#    restart: always
    container_name: tethys_in_docker_postgis
    image: ciwater/postgis:2.1.2
    ports:
      - "5435:5432"
#    volumes:
#      - ./postgis/var/log/:/var/log
    env_file: tethys_main.env

  tethys_in_docker_main:
#    restart: always
    container_name: tethys_in_docker_main
    build: ./tethys_main/
    image: tethys_in_docker_main
    ports:
      - "8000:8000"
    volumes:
      - ./tethys/:/tethys
      - ./tethys_main/settings.py:/tethys/tethys_apps/settings.py
      - ./tethys_main/patches/backends/hs_restclient_helper.py:/tethys/tethys_services/backends/hs_restclient_helper.py
      - ./tethys_main/patches/backends/hydroshare.py:/tethys/tethys_services/backends/hydroshare.py
      - ./tethys_main/patches/backends/hydroshare_beta.py:/tethys/tethys_services/backends/hydroshare_beta.py
      - ./tethys_main/patches/login.html:/tethys/templates/tethys_portal/accounts/login.html
      - ./tethys_main/:/tethys_main
      - ./tethys_main/gunicorn-supervisor.conf:/etc/supervisor/conf.d/gunicorn-supervisor.conf
      - ./static/:/var/www/tethys/static
      - ./apps/:/apps
      - ./logs/:/logs
     # - /projects/water/nwm/:/projects/water/nwm

    env_file: tethys_main.env
    environment:
      # change to False to activate production mode
      DEBUG: 'True'

    # start django development server
    #command: runuser -u tethys-user -g tethys-group /bin/bash /tethys_main/run-server
    #command: python manage.py runserver 0.0.0.0:8000

    # start gunicore server
    #command: /tethys_main/run-gunicorn

    # start supervisor + gunicorn
    command: /tethys_main/startup

    depends_on:
      - tethys_in_docker_postgis

  tethys_in_docker_nginx:
#    restart: always
    image: nginx:1.11.5
    #image: zhiyuli/nginx-extras-lua-json:1.10
    container_name: tethys_in_docker_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/:/certs
      - ./nginx/ssl.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/var/www/tethys/static
      - ./logs/:/logs
    depends_on:
      - tethys_in_docker_main
      - tethys_in_docker_geoserver

  tethys_in_docker_geoserver:
#    restart: always
    #image: ciwater/geoserver:2.8.2-clustered
    image: zhiyuli/geoserver:2.8.2-clustered-1.5
    container_name: tethys_in_docker_geoserver
    ports:
      - "8181:8181"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    env_file: ./geoserver/geoserver.env
    volumes:
      - ./logs/:/var/log/nginx
      - ./logs/:/var/geoserver/node1/logs
      - ./logs/:/var/geoserver/node2/logs
      - ./logs/:/var/geoserver/node3/logs
      - ./logs/:/var/geoserver/node4/logs
      - ./logs/:/var/log/supervisor

#volumes:
#  tethys_pgdata:
#    driver: local
