#!/usr/bin/env bash
echo "*** Rebuild Tethys in Docker ***"
sleep 3
docker stop $(docker ps -a -q -f name=tethys_in_docker*)
docker rm -f $(docker ps -a -q -f name=tethys_in_docker*)
docker rmi -f $(docker images | grep tethys_in_docker)

rm -rvf tethys_main/tethys_src/
mkdir tethys_main/tethys_src/
#git clone -b release-candidate-140-1 https://github.com/tethysplatform/tethys.git tethys_main/tethys_src
git clone https://github.com/tethysplatform/tethys.git tethys_main/tethys_src
cd tethys_main/tethys_src
# git checkout tags/1.3.3
git checkout release-candidate-140-1
cd ../../
cp -rf tethys_main/tethys_src/requirements.txt tethys_main/
docker-compose build
docker-compose up -d
sleep 10
docker exec -it tethys_in_docker_main python manage.py migrate
wait
docker exec -it tethys_in_docker_main python manage.py createsuperuser
wait
docker-compose stop
wait
docker-compose up -d
sleep 10
echo "Done. Visit 127.0.0.1:8000"