#!/usr/bin/env bash

docker exec -it tethys_in_docker_main bash -c "python /tethys/manage.py collectstatic -v 0 --noinput && \
                                               chown -R tethys-user:tethys-group /tethys && \
                                               chown -R tethys-user:tethys-group /apps && \
                                               chown -R tethys-user:tethys-group /var/www/tethys/static"
docker restart tethys_in_docker_main
docker restart tethys_in_docker_nginx