#!/usr/bin/env bash

### Local Config ###
CONFIG_FOLDER='./config'
CONFIG_FILE='config.yaml'
HOME_DIR=${PWD}

# Read config.yaml into environment
sed -e "s/:[^:\/\/]/=/g;s/$//g;s/ *=/=/g" ${CONFIG_FOLDER}/${CONFIG_FILE} > ${CONFIG_FOLDER}/config.sh
sed -i 's/#.*$//' ${CONFIG_FOLDER}/config.sh
sed -i '/^\s*$/d' ${CONFIG_FOLDER}/config.sh
while read line; do export $line; done < <(cat ${CONFIG_FOLDER}/config.sh)

############################### PostGIS #######################################
# postgis.env
sed -e 's/<TETHYS_POSTGIS_TETHYS_DEFAULT_PASS>/'"${TETHYS_POSTGIS_TETHYS_DEFAULT_PASS}"'/' \
    -e 's/<TETHYS_POSTGIS_TETHYS_DB_MANAGER_PASS>/'"${TETHYS_POSTGIS_TETHYS_DB_MANAGER_PASS}"'/' \
    -e 's/<TETHYS_POSTGIS_TETHYS_SUPER_PASS>/'"${TETHYS_POSTGIS_TETHYS_SUPER_PASS}"'/' \
    ./postgis/postgis.env_template >./postgis/postgis.env

############################### docker-compose.yml ####################################
cp -f ./docker-compose.yml_template ./docker-compose.yml

sed -i 's/<TETHYS_NGINX_DOMAIN_NAME>/'"${TETHYS_NGINX_DOMAIN_NAME}"'/' \
       ./docker-compose.yml

if [[ ${TETHYS_MAIN_MOUNT_RENCI_FOLDER} =~ ^[Yy]$ ]]
then
    sed -i 's!#_#_#_#<TETHYS_MAIN_MOUNT_RENCI_FOLDER>#_#_#_#!- '${TETHYS_MAIN_MOUNT_RENCI_FOLDER_PATH}:${TETHYS_MAIN_MOUNT_RENCI_FOLDER_PATH}'!' \
        ./docker-compose.yml
fi

if [[ ${TETHYS_NGINX_SSL_CERT_USE_PRODUCTION} =~ ^[Yy]$ ]]
then
    sed -i 's!#_#_#_#<TETHYS_NGINX_SSL_CERT_CHAIN_CRT>#_#_#_#!- '${TETHYS_NGINX_SSL_CERT_CHAIN_CRT}'!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_NGINX_SSL_CERT_FILE_SERVER_CRT>#_#_#_#!- '${TETHYS_NGINX_SSL_CERT_FILE_SERVER_CRT}'!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_NGINX_SSL_CERT_FILE_SERVER_KEY>#_#_#_#!- '${TETHYS_NGINX_SSL_CERT_FILE_SERVER_KEY}'!' \
        ./docker-compose.yml
fi


if [[ ${TETHYS_POSTGIS_OPEN_PORTS} =~ ^[Yy]$ ]]
then
    sed -i 's!#_#_#_#<TETHYS_POSTGIS_OPEN_PORTS>#_#_#_#!ports:!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_POSTGIS_MAP_INTERNAL_5432_TO>#_#_#_#!- "'${TETHYS_POSTGIS_MAP_INTERNAL_5432_TO}':5432"!' \
        ./docker-compose.yml
fi

if [[ ${TETHYS_MAIN_OPEN_PORTS} =~ ^[Yy]$ ]]
then
    sed -i 's!#_#_#_#<TETHYS_MAIN_OPEN_PORTS>#_#_#_#!ports:!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_MAIN_MAP_INTERNAL_8000_TO>#_#_#_#!- "'${TETHYS_MAIN_MAP_INTERNAL_8000_TO}':8000"!' \
        ./docker-compose.yml
fi

if [[ ${TETHYS_MAIN_OPEN_PORTS} =~ ^[Yy]$ ]]
then
    sed -i 's!#_#_#_#<TETHYS_MAIN_OPEN_PORTS>#_#_#_#!ports:!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_MAIN_MAP_INTERNAL_5555_TO>#_#_#_#!- "'${TETHYS_MAIN_MAP_INTERNAL_5555_TO}':5555"!' \
        ./docker-compose.yml
fi

if [[ ${TETHYS_GEOSERVER_OPEN_PORTS} =~ ^[Yy]$ ]]
then
    sed -i 's!#_#_#_#<TETHYS_GEOSERVER_OPEN_PORTS>#_#_#_#!ports:!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_GEOSERVER_MAP_INTERNAL_8181_TO>#_#_#_#!- "'${TETHYS_GEOSERVER_MAP_INTERNAL_8181_TO}':8181"!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_GEOSERVER_MAP_INTERNAL_8081_TO>#_#_#_#!- "'${TETHYS_GEOSERVER_MAP_INTERNAL_8081_TO}':8081"!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_GEOSERVER_MAP_INTERNAL_8082_TO>#_#_#_#!- "'${TETHYS_GEOSERVER_MAP_INTERNAL_8082_TO}':8082"!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_GEOSERVER_MAP_INTERNAL_8083_TO>#_#_#_#!- "'${TETHYS_GEOSERVER_MAP_INTERNAL_8083_TO}':8083"!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_GEOSERVER_MAP_INTERNAL_8084_TO>#_#_#_#!- "'${TETHYS_GEOSERVER_MAP_INTERNAL_8084_TO}':8084"!' \
        ./docker-compose.yml
fi

if [[ ${TETHYS_N52WPS_OPEN_PORTS} =~ ^[Yy]$ ]]
then
    sed -i 's!#_#_#_#<TETHYS_N52WPS_OPEN_PORTS>#_#_#_#!ports:!' \
        ./docker-compose.yml
    sed -i 's!#_#_#_#<TETHYS_N52WPS_MAP_INTERNAL_8080_TO>#_#_#_#!- "'${TETHYS_N52WPS_MAP_INTERNAL_8080_TO}':8080"!' \
        ./docker-compose.yml
fi

if [ ${TETHYS_MAIN_DEBUG} = False ]
then
    sed -i 's/#_#_TETHYS_MAIN_USE_GUNICORN_SERVER_#_#//' \
        ./docker-compose.yml
else
    sed -i 's/#_#_TETHYS_MAIN_USE_DJANGO_TESTING_SERVER_#_#//' \
        ./docker-compose.yml
fi

###############################  Nginx ###############################
# ssl.conf
cp -f ./nginx/ssl.conf_template ./nginx/ssl.conf

sed -i 's/<TETHYS_NGINX_DOMAIN_NAME>/'"${TETHYS_NGINX_DOMAIN_NAME}"'/' \
       ./nginx/ssl.conf

if [ ${TETHYS_MAIN_DEBUG} = False ]
then
    sed -i 's/#_#_ENABLE_NGINX_ERROR_PAGE_#_#//' \
        ./nginx/ssl.conf
fi

if [ ${TETHYS_MAIN_DEBUG} = False ]
then
    sed -i 's/#_#_ENABLE_NGINX_STATIC_FILES_#_#//' \
        ./nginx/ssl.conf
fi

if [[ ${TETHYS_NGINX_MAINTENANCE_ON} =~ ^[Yy]$ ]]
then
    sed -i 's/#_#TETHYS_NGINX_MAINTENANCE_ON#_#//' \
        ./nginx/ssl.conf
fi

###############################  GeoServer ###############################
# geoserver.env
sed -e 's/<TETHYS_GEOSERVER_ENABLED_NODES>/'"${TETHYS_GEOSERVER_ENABLED_NODES}"'/' \
    -e 's/<TETHYS_GEOSERVER_REST_NODES>/'"${TETHYS_GEOSERVER_REST_NODES}"'/' \
    -e 's/<TETHYS_GEOSERVER_NUM_CORES>/'"${TETHYS_GEOSERVER_NUM_CORES}"'/' \
    -e 's/<TETHYS_GEOSERVER_MAX_TIMEOUT>/'"${TETHYS_GEOSERVER_MAX_TIMEOUT}"'/' \
    -e 's/<TETHYS_GEOSERVER_MAX_MEMORY>/'"${TETHYS_GEOSERVER_MAX_MEMORY}"'/' \
    -e 's/<TETHYS_GEOSERVER_MIN_MEMORY>/'"${TETHYS_GEOSERVER_MIN_MEMORY}"'/' \
    -e 's/<TETHYS_GEOSERVER_GEOSERVER_FILEBROWSER_HIDEFS>/'"${TETHYS_GEOSERVER_GEOSERVER_FILEBROWSER_HIDEFS}"'/' \
    ./geoserver/geoserver.env_template >./geoserver/geoserver.env

###############################  Tethys_Main ###############################
# settings.py
sed -e 's/<TETHYS_MAIN_SECRET_KEY>/'"${TETHYS_MAIN_SECRET_KEY}"'/' \
    -e 's/<TETHYS_MAIN_DEBUG>/'"${TETHYS_MAIN_DEBUG}"'/' \
    -e 's/<TETHYS_POSTGIS_TETHYS_DEFAULT_PASS>/'"${TETHYS_POSTGIS_TETHYS_DEFAULT_PASS}"'/' \
    -e 's/<TETHYS_POSTGIS_TETHYS_DB_MANAGER_PASS>/'"${TETHYS_POSTGIS_TETHYS_DB_MANAGER_PASS}"'/' \
    -e 's/<TETHYS_POSTGIS_TETHYS_SUPER_PASS>/'"${TETHYS_POSTGIS_TETHYS_SUPER_PASS}"'/' \
    -e 's/<TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_KEY>/'"${TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_KEY}"'/' \
    -e 's/<TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_SECRET>/'"${TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_SECRET}"'/' \
    -e 's/<TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_BETA_KEY>/'"${TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_BETA_KEY}"'/' \
    -e 's/<TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_BETA_SECRET>/'"${TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_BETA_SECRET}"'/' \
    -e 's/<TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_PLAYGROUND_KEY>/'"${TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_PLAYGROUND_KEY}"'/' \
    -e 's/<TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_PLAYGROUND_SECRET>/'"${TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_PLAYGROUND_SECRET}"'/' \
    ./tethys_main/settings.py_template >./tethys_main/settings.py

sed -i 's!<TETHYS_MAIN_BYPASS_TETHYS_HOME_PAGE>!'${TETHYS_MAIN_BYPASS_TETHYS_HOME_PAGE}'!' \
        ./tethys_main/settings.py
sed -i 's!<TETHYS_MAIN_ENABLE_OPEN_SIGNUP>!'${TETHYS_MAIN_ENABLE_OPEN_SIGNUP}'!' \
        ./tethys_main/settings.py
sed -i 's!<TETHYS_MAIN_LOGIN_URL>!'${TETHYS_MAIN_LOGIN_URL}'!' \
        ./tethys_main/settings.py

if [[ ${TETHYS_MAIN_HYDROSHARE_BACKEND} =~ ^[Yy]$ ]]
then
    sed -i 's/#_#_#_#<TETHYS_MAIN_HYDROSHARE_BACKEND>#_#_#_#/'"${TETHYS_MAIN_HYDROSHARE_BACKEND_MODULE}"'/' \
        ./tethys_main/settings.py
fi

if [[ ${TETHYS_MAIN_HYDROSHARE_BETA_BACKEND} =~ ^[Yy]$ ]]
then
    sed -i 's/#_#_#_#<TETHYS_MAIN_HYDROSHARE_BETA_BACKEND>#_#_#_#/'"${TETHYS_MAIN_HYDROSHARE_BETA_BACKEND_MODULE}"'/' \
        ./tethys_main/settings.py
fi

if [[ ${TETHYS_MAIN_HYDROSHARE_PLAYGROUND_BACKEND} =~ ^[Yy]$ ]]
then
    sed -i 's/#_#_#_#<TETHYS_MAIN_HYDROSHARE_PLAYGROUND_BACKEND>#_#_#_#/'"${TETHYS_MAIN_HYDROSHARE_PLAYGROUND_BACKEND_MODULE}"'/' \
        ./tethys_main/settings.py
fi

if [[ ${TETHYS_GEOSERVER_FORCE_SSL} =~ ^[Yy]$ ]]
then
    sed -i 's!<TETHYS_GEOSERVER_URL_BASE>!"https://'${TETHYS_NGINX_DOMAIN_NAME}:${TETHYS_GEOSERVER_SSL_ON_PORT}'"!' \
        ./tethys_main/settings.py
    sed -i 's!<TETHYS_GEOSERVER_URL_SSL_BASE>!"https://'${TETHYS_NGINX_DOMAIN_NAME}:${TETHYS_GEOSERVER_SSL_ON_PORT}'"!' \
        ./tethys_main/settings.py
else
    sed -i 's!<TETHYS_GEOSERVER_URL_BASE>!"http://'${TETHYS_NGINX_DOMAIN_NAME}:${TETHYS_GEOSERVER_HTTP_ON_PORT}'"!' \
        ./tethys_main/settings.py
    sed -i 's!<TETHYS_GEOSERVER_URL_SSL_BASE>!"https://'${TETHYS_NGINX_DOMAIN_NAME}:${TETHYS_GEOSERVER_SSL_ON_PORT}'"!' \
        ./tethys_main/settings.py
fi

sed -i 's!<TETHYS_GEOSERVER_USER_NAME>!"'${TETHYS_GEOSERVER_USER_NAME}'"!' \
        ./tethys_main/settings.py
sed -i 's!<TETHYS_GEOSERVER_USER_PASSWORD>!"'${TETHYS_GEOSERVER_USER_PASSWORD}'"!' \
        ./tethys_main/settings.py

if [ ${TETHYS_MAIN_DEBUG} = False ]
then
    sed -i 's!<TETHYS_NGINX_DOMAIN_NAME>!'${TETHYS_NGINX_DOMAIN_NAME}'!' \
        ./tethys_main/settings.py
else
    sed -i 's!<TETHYS_NGINX_DOMAIN_NAME>!'*'!' \
        ./tethys_main/settings.py
fi

###############################  Tethys_N52WPS ###############################
# n52wps.env
cp -f ./n52wps/n52wps.env_template ./n52wps/n52wps.env
sed -i 's/<TETHYS_N52WPS_USERNAME>/'"${TETHYS_N52WPS_USERNAME}"'/' \
        ./n52wps/n52wps.env
sed -i 's/<TETHYS_N52WPS_PASSWORD>/'"${TETHYS_N52WPS_PASSWORD}"'/' \
        ./n52wps/n52wps.env

echo "All containers must restart to apply the changes: ./tethys_restart all"