#!/usr/bin/env bash
echo "*** Rebuild Tethys in Docker ***"
echo "Remove existing containers...."
docker stop $(docker ps -a -q -f name=tethys_in_docker*)
docker rm -f $(docker ps -a -q -f name=tethys_in_docker*)
# remove all unused data volumes
echo "Remove unused data volumes...."
docker volume rm $(docker volume ls -qf dangling=true)
# docker rmi -f $(docker images | grep tethys_in_docker)
echo "Clone Tethys repo...."
rm -rf tethys
git clone https://github.com/tethysplatform/tethys.git
cd tethys
# git checkout tags/1.3.3
git checkout release-candidate-140-1
cd ../
cp -f tethys/requirements.txt tethys_main/
echo "Build images...."
docker-compose build
echo "Start containers...."
docker-compose up -d
wait
sleep 10
echo "Migrate DB...."
#docker-compose run --rm tethys_in_docker_main bash -c "/bin/bash build-tethys && \
#                                                       python manage.py migrate && \
#                                                       python manage.py createsuperuser"

docker exec -it tethys_in_docker_main bash -c "/bin/bash build-tethys && \
                                                       python manage.py migrate && \
                                                       python manage.py createsuperuser"
# docker exec -it tethys_in_docker_main python manage.py migrate
# docker exec -it tethys_in_docker_main python manage.py createsuperuser
echo "Restart containers...."
docker-compose restart
wait
echo "Done. Visit 127.0.0.1:8000"