#!/usr/bin/env bash

APP_NAME=$1
echo $APP_NAME

docker exec -it tethys_in_docker_main bash -c "cd /apps && \
                                               tethys scaffold $APP_NAME &&\
                                               chown -R tethys-user:tethys-group /apps"