#!/usr/bin/env bash

docker exec -it tethys_in_docker_main bash -c "python /tethys/manage.py collectstatic -v 0 --noinput && \
                                               chown -R tethys-user:tethys-group /tethys && \
                                               chown -R tethys-user:tethys-group /apps && \
                                               tethys manage collectworkspaces --manage=/tethys/manage.py && \
                                               chown -R tethys-user:tethys-group /var/www/tethys/workspaces && \
                                               chown -R tethys-user:tethys-group /var/www/tethys/static"

./tethys_change_permission
docker restart tethys_in_docker_main
docker restart tethys_in_docker_nginx