#!/usr/bin/env bash
docker exec -it tethys_in_docker_main bash -c "chown -R tethys-user:tethys-group /tethys && \
                                               chown -R tethys-user:tethys-group /apps && \
                                               chown -R tethys-user:tethys-group /var/www/tethys/static && \
                                               chown -R tethys-user:tethys-group /logs && \
                                               chown -R tethys-user:tethys-group /home/tethys-user && \
                                               chmod -R 777 /logs"

## /projects/* files are mounted into Ubuntu VM first, then get mounted into container,
## these files are owned by root:999, which tethys-user cannot access
## ls -al /projects/water/nwm/data/nomads/
## groupadd -g 999 vm-mounted-group
## usermod -a -G vm-mounted-group tethys-user
## id tethys-user

