#!/usr/bin/env bash
echo "*** Rebuild Tethys_in_Docker ***"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR

USER_NAME=$(whoami)
USER_ID=$(id -u)
GROUP_ID=$(id -g)

echo "User Name"
echo $USER_NAME
echo "User ID"
echo $USER_ID
echo "Group ID"
echo $GROUP_ID

if [  $# -eq 0 ]
then
    branch_name=release-candidate-140-1
else
    branch_name=$1
fi

echo "Stop running containers...."
docker-compose stop

echo "Remove existing containers...."
docker rm -f tethys_in_docker_nginx
docker rm -f tethys_in_docker_main
docker rm -f tethys_in_docker_postgis
docker rm -f tethys_in_docker_geoserver
docker rmi tethys_in_docker_main

# remove all unused docker data volumes
echo "Remove unused docker data volumes...."
docker volume rm $(docker volume ls -qf dangling=true)

# create required folders
rm -rf tethys/*
rm -rf tethys/.*
rm -rf static/*
rm -rf logs/*

mkdir -p tethys
mkdir -p static
mkdir -p logs

echo "Clone Tethys repo...."
git clone https://github.com/tethysplatform/tethys.git tethys
cd tethys
echo "Using branch " $branch_name
git checkout $branch_name
cd ..
cp -f tethys/requirements.txt tethys_main/

echo "Build images...."
docker-compose build

echo "Start containers...."
docker-compose up -d
sleep 10
./tethys_db_restore

echo "Running init-tethys script"
docker exec -it tethys_in_docker_main /bin/bash /tethys_main/init-tethys $USER_ID $GROUP_ID

echo "Restart main container...."
docker restart tethys_in_docker_main
wait
echo "Rebuild Done."
