#!/usr/bin/env bash

install_one_app() {
    echo "install_one_app"
    echo $1
    app_folder_name=$1
    echo $app_folder
    echo "Installing" $app_folder "..."
    docker exec -it tethys_in_docker_main bash -c "cd /apps/$app_folder_name && \
                                               python setup.py develop"
    #docker exec -it tethys_in_docker_main bash -c "tethys syncstores all --manage /tethys/manage.py"
}

install_all_apps() {
    echo "install_all_apps"
    cd apps
    for f in */; do
        if [ -d ${f} ]; then
            # Will not run if no directories are available
            app_folder_name=${f}
            echo "Installing" ${app_folder_name} "..."
            docker exec -it tethys_in_docker_main bash -c "cd /apps/$app_folder_name && \
                                                           python setup.py develop"
            #docker exec -it tethys_in_docker_main bash -c "tethys syncstores all --manage /tethys/manage.py"
        fi
    done
}

echo $#
echo $1

docker exec -it tethys_in_docker_main bash -c "python /tethys/setup.py develop"

if [  $# -eq 0 ]
then
    # install all apps in folder apps
    install_all_apps
else
    # install a specific app
    install_one_app  $1
fi

docker exec -it tethys_in_docker_main bash -c "tethys syncstores all --manage /tethys/manage.py"

docker exec -it tethys_in_docker_main bash -c "python /tethys/manage.py collectstatic -v 0 --noinput && \
                                               chown -R tethys-user:tethys-group /tethys && \
                                               chown -R tethys-user:tethys-group /apps && \
                                               chown -R tethys-user:tethys-group /var/www/tethys/static"
echo "Restart Tethys main container"
docker restart tethys_in_docker_main
docker restart tethys_in_docker_nginx
echo "Done"